# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
hostname: bigbang.dev

nameOverride: "hello-world"
fullnameOverride: "hello-world"

service:
  port: 80
  deployVirtualService: true
  
istio:
  gateways:
  - istio-system/main

image:
  repository: rancher/hello-world
  pullPolicy: Always
  tag: v0.1.2
  includeReadinessProbe: false

virtualServicePort: 80
replicas: 2

secretStore:
  provider: azure
  enabled: true
  usePodIdentity: false
  useVMManagedIdentity: true
  secrets:
  identity:
