{{- if .Values.secretStore.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ default .Release.Namespace }}
spec:
  provider: {{ .Values.secretStore.provider }}
  secretObjects:
    {{- range $secret := .Values.secretStore.secrets }}
    - secretName: {{ $secret.alias }}
      type: Opaque
      data:
        - objectName: {{ $secret.alias }}
          key: {{ $secret.alias }}
    {{- end }}
  parameters:
    usePodIdentity: {{ .Values.secretStore.usePodIdentity }}
    useVMManagedIdentity: {{ .Values.secretStore.useVMManagedIdentity }}
    userAssignedIdentityID: {{ .Values.secretStore.identity.clientId }}
    keyvaultName: {{ .Values.secretStore.keyvaultName }}
    objects:  |
      array:
        {{- range $secret := .Values.secretStore.secrets }}
        - |
          objectName: {{ $secret.objectName }}
          objectAlias: {{ $secret.alias }}
          objectType: secret
        {{- end }}
    tenantId: {{ .Values.secretStore.tenantId }}
{{- end }}